[package]
name = "tokio-retry"
version = "0.3.0"
authors = ["Sam Rijs <srijs@airpost.net>", "Konstantin Stepanov <me@kstep.me>"]
description = "Extensible, asynchronous retry behaviours for futures/tokio"
license = "MIT"
readme = "README.md"
repository = "https://github.com/srijs/rust-tokio-retry"
documentation = "https://docs.rs/tokio-retry"
keywords = ["futures", "tokio", "retry", "exponential", "backoff"]
edition = "2018"

[dependencies]
rand = "0.7.2"
tokio = { version = "0.2", features = ["time"] }
pin-utils = "0.1.0-alpha"

[dev-dependencies]
quickcheck = "0.9.0"
futures = "0.3.1"
